Mise à jour des délais
etimou/frisquet-arduino pull request #1
Opened 2020-11-06 16:31 UTC by Today2000

Je te propose de mettre à jour les délais de cycle pour mettre toutes les variables au début.
J'ai également adapté pour définir un nouveau cycle de protection de la chaudière comme c'est le cas avec la télécommande pour eviter qu'elle se mette à chauffer sans arreter si le serveur MQTT est down et n'envoi plus de commande.

PS: excuse moi si ce n'est pas très propre, je debute, je vais essayer de m'améliorer, je suis preneur de tes conseils ;-)

2020-11-06 17:57 UTC, etimou commented
Merci pour ta proposition. Je ne suis pas très à l'aise avec les pull request. Peut-être que c'est toi qui peut m'aider.
qq commentaires:
- mettre les délais constants en const (c'est plus propre). Ou des #define
- pour la verif de communication MQTT, perso il m'arrive de ne pas envoyer de commandes pendant 12h voire plus. Il faudrait désactiver si la valeur est 0.
- dans le cas de perte de communication, on envoie plus rien à la chaudière. Je me demande si c'est pas mieux d'envoyer une commande à 0.

Je ne sais pas trop comment m'y prendre. A toi de modifier ton pull request ou à moi d'accepter en faisant des modifs...

2020-11-06 20:44 UTC, Today2000 commented
Moi aussi pas très a l aise avec mes pull request;-) je pense qu il y aura peu de modif avant d avoir une solution stable. Je te propose de faire les modifs.

Ok pour les define

Quand tu retires les piles de la télécommande au bout de 15 min 20min la chaudière ce met en erreur car ne reçoit plus d info. Je garderai le meme principe (donc pas de 0)
Je pense que c est vraiment une bonne pratique pour la sécurité. Il faut a minima l implémenter quitte a pouvoir le désactiver.
Ça serait vraiment dommage qu une chaudiere chauffe au max plusieurs jours...

Il faut mieux que le serveur mqtt répète l info régulièrement (avec un scénario si besoin)


++

2020-11-08 09:15 UTC, etimou requested changes

2020-11-08 09:15 UTC, etimou commented on frisquet-mqtt.ino
>  int delayCycleMsg =  60000; //report temperature every minute
```suggestion
int delayCycleCmd; //  This variable contains the delay for the next command to the boiler (if no command is received via MQTT)
#define DELAY_CYCLE_CMD 240000 // delay between 2 commands (4min)
#define DELAY_CYCLE_CMD_INIT 240000// delay for the 1st command after startup (4min)
#define DELAY_REPEAT_CMD 20000 // when a new command is issued, it is repeated after this delay (20s)
#define DELAY_TIMEOUT_CMD_MQTT 900000 // 15min Max delay without Mqtt msg ---PROTECTION OVERHEATING ---- (Same as remote)
#define DELAY_CYCLE_MSG 60000 // reports temperature every minute
int delayCycleCmd=DELAY_CYCLE_CMD_INIT // init
```

2020-11-08 09:15 UTC, etimou commented on frisquet-mqtt.ino
> +    delayCycleCmd = delayCycleCmdPreheat;
```suggestion
delayCycleCmd = DELAY_REPEAT_CMD;
```

2020-11-08 09:15 UTC, etimou commented on frisquet-mqtt.ino
> +    delayCycleCmd = delayCycleCmdInit;
```suggestion
delayCycleCmd = DELAY_CYCLE_CMD;
```

2020-11-09 13:59 UTC, Today2000 commented
Il faut que tu acceptes et fusion les changements que tu as fais dans ta branche

2020-11-09 16:15 UTC, merged